# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'popcnv_main_formkbAvzw.ui'
##
## Created by: Qt User Interface Compiler version 6.6.2
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
                            QMetaObject, QObject, QPoint, QRect,
                            QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QBrush, QColor, QConicalGradient, QCursor,
                           QFont, QFontDatabase, QGradient, QIcon,
                           QImage, QKeySequence, QLinearGradient, QPainter,
                           QPalette, QPixmap, QRadialGradient, QTransform)
from PySide6.QtWidgets import (QApplication, QComboBox, QGraphicsView, QGroupBox,
                               QHeaderView, QLabel, QLineEdit, QPushButton,
                               QSizePolicy, QTabWidget, QTableView, QWidget)
from pop_cnv.ui.custom_control import DragLineEdit, ControlGraphicsView


class Ui_frmMain(object):
    def setupUi(self, frmMain):
        if not frmMain.objectName():
            frmMain.setObjectName(u"frmMain")
        frmMain.resize(832, 816)
        self.grpInput = QGroupBox(frmMain)
        self.grpInput.setObjectName(u"grpInput")
        self.grpInput.setGeometry(QRect(10, 10, 811, 131))
        font = QFont()
        font.setPointSize(14)
        font.setBold(True)
        self.grpInput.setFont(font)
        self.btn_load_gene_list = QPushButton(self.grpInput)
        self.btn_load_gene_list.setObjectName(u"btn_load_gene_list")
        self.btn_load_gene_list.setGeometry(QRect(760, 80, 41, 41))
        font1 = QFont()
        font1.setPointSize(16)
        font1.setBold(False)
        self.btn_load_gene_list.setFont(font1)
        self.text_gene_list_file_path = DragLineEdit(self.grpInput)
        self.text_gene_list_file_path.setObjectName(u"text_gene_list_file_path")
        self.text_gene_list_file_path.setGeometry(QRect(510, 80, 241, 41))
        font2 = QFont()
        font2.setPointSize(14)
        font2.setBold(False)
        self.text_gene_list_file_path.setFont(font2)
        self.label_4 = QLabel(self.grpInput)
        self.label_4.setObjectName(u"label_4")
        self.label_4.setGeometry(QRect(420, 80, 81, 31))
        font3 = QFont()
        font3.setPointSize(12)
        font3.setBold(False)
        self.label_4.setFont(font3)
        self.text_seq_depth_file_path = DragLineEdit(self.grpInput)
        self.text_seq_depth_file_path.setObjectName(u"text_seq_depth_file_path")
        self.text_seq_depth_file_path.setGeometry(QRect(110, 80, 241, 41))
        self.text_seq_depth_file_path.setFont(font2)
        self.btn_load_mosdepth = QPushButton(self.grpInput)
        self.btn_load_mosdepth.setObjectName(u"btn_load_mosdepth")
        self.btn_load_mosdepth.setGeometry(QRect(760, 30, 41, 41))
        self.btn_load_mosdepth.setFont(font1)
        self.btn_load_seqdepth = QPushButton(self.grpInput)
        self.btn_load_seqdepth.setObjectName(u"btn_load_seqdepth")
        self.btn_load_seqdepth.setGeometry(QRect(360, 80, 41, 41))
        self.btn_load_seqdepth.setFont(font1)
        self.btn_load_gnome = QPushButton(self.grpInput)
        self.btn_load_gnome.setObjectName(u"btn_load_gnome")
        self.btn_load_gnome.setGeometry(QRect(360, 30, 41, 41))
        self.btn_load_gnome.setFont(font1)
        self.label_2 = QLabel(self.grpInput)
        self.label_2.setObjectName(u"label_2")
        self.label_2.setGeometry(QRect(420, 30, 81, 31))
        self.label_2.setFont(font3)
        self.label_3 = QLabel(self.grpInput)
        self.label_3.setObjectName(u"label_3")
        self.label_3.setGeometry(QRect(10, 80, 81, 31))
        self.label_3.setFont(font3)
        self.text_mosdepth_folder_path = DragLineEdit(self.grpInput)
        self.text_mosdepth_folder_path.setObjectName(u"text_mosdepth_folder_path")
        self.text_mosdepth_folder_path.setGeometry(QRect(510, 30, 241, 41))
        self.text_mosdepth_folder_path.setFont(font2)
        self.text_genome_file_path = DragLineEdit(self.grpInput)
        self.text_genome_file_path.setObjectName(u"text_genome_file_path")
        self.text_genome_file_path.setGeometry(QRect(110, 30, 241, 41))
        self.text_genome_file_path.setFont(font2)
        self.label = QLabel(self.grpInput)
        self.label.setObjectName(u"label")
        self.label.setGeometry(QRect(10, 30, 81, 31))
        self.label.setFont(font3)
        self.grpSettings = QGroupBox(frmMain)
        self.grpSettings.setObjectName(u"grpSettings")
        self.grpSettings.setGeometry(QRect(10, 150, 811, 131))
        self.grpSettings.setFont(font)
        self.label_5 = QLabel(self.grpSettings)
        self.label_5.setObjectName(u"label_5")
        self.label_5.setGeometry(QRect(10, 30, 101, 31))
        self.label_5.setFont(font3)
        self.cbox_wild_group = QComboBox(self.grpSettings)
        self.cbox_wild_group.setObjectName(u"cbox_wild_group")
        self.cbox_wild_group.setGeometry(QRect(110, 30, 291, 41))
        self.cbox_wild_group.setFont(font2)
        self.label_6 = QLabel(self.grpSettings)
        self.label_6.setObjectName(u"label_6")
        self.label_6.setGeometry(QRect(420, 30, 81, 31))
        self.label_6.setFont(font3)
        self.cbox_threads = QComboBox(self.grpSettings)
        self.cbox_threads.setObjectName(u"cbox_threads")
        self.cbox_threads.setGeometry(QRect(510, 30, 291, 41))
        self.cbox_threads.setFont(font2)
        self.text_wrkdir = DragLineEdit(self.grpSettings)
        self.text_wrkdir.setObjectName(u"text_wrkdir")
        self.text_wrkdir.setGeometry(QRect(110, 80, 641, 41))
        self.text_wrkdir.setFont(font2)
        self.btn_load_wrkdir = QPushButton(self.grpSettings)
        self.btn_load_wrkdir.setObjectName(u"btn_load_wrkdir")
        self.btn_load_wrkdir.setGeometry(QRect(760, 80, 41, 41))
        self.btn_load_wrkdir.setFont(font1)
        self.label_7 = QLabel(self.grpSettings)
        self.label_7.setObjectName(u"label_7")
        self.label_7.setGeometry(QRect(10, 80, 101, 31))
        self.label_7.setFont(font3)
        self.grpOutput = QGroupBox(frmMain)
        self.grpOutput.setObjectName(u"grpOutput")
        self.grpOutput.setGeometry(QRect(10, 350, 811, 461))
        self.grpOutput.setFont(font)
        self.tabOutput = QTabWidget(self.grpOutput)
        self.tabOutput.setObjectName(u"tabOutput")
        self.tabOutput.setGeometry(QRect(10, 30, 791, 421))
        self.tab_pic = QWidget()
        self.tab_pic.setObjectName(u"tab_pic")
        self.graphPreview = ControlGraphicsView(self.tab_pic)
        self.graphPreview.setObjectName(u"graphPreview")
        self.graphPreview.setGeometry(QRect(10, 10, 761, 311))
        self.label_9 = QLabel(self.tab_pic)
        self.label_9.setObjectName(u"label_9")
        self.label_9.setGeometry(QRect(10, 330, 51, 31))
        self.label_9.setFont(font3)
        self.cbox_pic_data_type = QComboBox(self.tab_pic)
        self.cbox_pic_data_type.setObjectName(u"cbox_pic_data_type")
        self.cbox_pic_data_type.setGeometry(QRect(60, 330, 71, 41))
        self.cbox_pic_data_type.setFont(font2)
        self.label_10 = QLabel(self.tab_pic)
        self.label_10.setObjectName(u"label_10")
        self.label_10.setGeometry(QRect(140, 330, 71, 31))
        self.label_10.setFont(font3)
        self.cbox_pic_smp = QComboBox(self.tab_pic)
        self.cbox_pic_smp.setObjectName(u"cbox_pic_smp")
        self.cbox_pic_smp.setGeometry(QRect(210, 330, 71, 41))
        self.cbox_pic_smp.setFont(font2)
        self.cbox_pic_chr = QComboBox(self.tab_pic)
        self.cbox_pic_chr.setObjectName(u"cbox_pic_chr")
        self.cbox_pic_chr.setGeometry(QRect(330, 330, 71, 41))
        self.cbox_pic_chr.setFont(font2)
        self.label_11 = QLabel(self.tab_pic)
        self.label_11.setObjectName(u"label_11")
        self.label_11.setGeometry(QRect(290, 330, 71, 31))
        self.label_11.setFont(font3)
        self.btn_export_pic = QPushButton(self.tab_pic)
        self.btn_export_pic.setObjectName(u"btn_export_pic")
        self.btn_export_pic.setGeometry(QRect(660, 330, 111, 41))
        self.btn_export_pic.setFont(font1)
        self.btn_draw_pic = QPushButton(self.tab_pic)
        self.btn_draw_pic.setObjectName(u"btn_draw_pic")
        self.btn_draw_pic.setGeometry(QRect(540, 330, 111, 41))
        self.btn_draw_pic.setFont(font1)
        self.tabOutput.addTab(self.tab_pic, "")
        self.tab_table = QWidget()
        self.tab_table.setObjectName(u"tab_table")
        self.tablePreview = QTableView(self.tab_table)
        self.tablePreview.setObjectName(u"tablePreview")
        self.tablePreview.setGeometry(QRect(10, 10, 761, 311))
        self.btn_save_table = QPushButton(self.tab_table)
        self.btn_save_table.setObjectName(u"btn_save_table")
        self.btn_save_table.setGeometry(QRect(660, 330, 111, 41))
        self.btn_save_table.setFont(font1)
        self.btn_preview_table = QPushButton(self.tab_table)
        self.btn_preview_table.setObjectName(u"btn_preview_table")
        self.btn_preview_table.setGeometry(QRect(540, 330, 111, 41))
        self.btn_preview_table.setFont(font1)
        self.cbox_table_smp = QComboBox(self.tab_table)
        self.cbox_table_smp.setObjectName(u"cbox_table_smp")
        self.cbox_table_smp.setGeometry(QRect(210, 330, 71, 41))
        self.cbox_table_smp.setFont(font2)
        self.label_12 = QLabel(self.tab_table)
        self.label_12.setObjectName(u"label_12")
        self.label_12.setGeometry(QRect(10, 330, 51, 31))
        self.label_12.setFont(font3)
        self.label_13 = QLabel(self.tab_table)
        self.label_13.setObjectName(u"label_13")
        self.label_13.setGeometry(QRect(290, 330, 71, 31))
        self.label_13.setFont(font3)
        self.label_14 = QLabel(self.tab_table)
        self.label_14.setObjectName(u"label_14")
        self.label_14.setGeometry(QRect(140, 330, 71, 31))
        self.label_14.setFont(font3)
        self.cbox_table_data_type = QComboBox(self.tab_table)
        self.cbox_table_data_type.setObjectName(u"cbox_table_data_type")
        self.cbox_table_data_type.setGeometry(QRect(60, 330, 71, 41))
        self.cbox_table_data_type.setFont(font2)
        self.cbox_table_chr = QComboBox(self.tab_table)
        self.cbox_table_chr.setObjectName(u"cbox_table_chr")
        self.cbox_table_chr.setGeometry(QRect(330, 330, 71, 41))
        self.cbox_table_chr.setFont(font2)
        self.tabOutput.addTab(self.tab_table, "")
        self.btn_run = QPushButton(frmMain)
        self.btn_run.setObjectName(u"btn_run")
        self.btn_run.setGeometry(QRect(10, 300, 811, 41))
        self.btn_run.setFont(font1)

        self.retranslateUi(frmMain)

        self.tabOutput.setCurrentIndex(0)

        QMetaObject.connectSlotsByName(frmMain)

    # setupUi

    def retranslateUi(self, frmMain):
        frmMain.setWindowTitle(QCoreApplication.translate("frmMain", u"popCNV", None))
        self.grpInput.setTitle(QCoreApplication.translate("frmMain", u"Input files", None))
        self.btn_load_gene_list.setText(QCoreApplication.translate("frmMain", u"...", None))
        self.text_gene_list_file_path.setText("")
        self.label_4.setText(QCoreApplication.translate("frmMain", u"Gene list:", None))
        self.text_seq_depth_file_path.setText("")
        self.btn_load_mosdepth.setText(QCoreApplication.translate("frmMain", u"...", None))
        self.btn_load_seqdepth.setText(QCoreApplication.translate("frmMain", u"...", None))
        self.btn_load_gnome.setText(QCoreApplication.translate("frmMain", u"...", None))
        self.label_2.setText(QCoreApplication.translate("frmMain", u"Mosdepth:", None))
        self.label_3.setText(QCoreApplication.translate("frmMain", u"Seq depth:", None))
        self.text_mosdepth_folder_path.setText("")
        self.text_genome_file_path.setText("")
        self.label.setText(QCoreApplication.translate("frmMain", u"Genome:", None))
        self.grpSettings.setTitle(QCoreApplication.translate("frmMain", u"Settings", None))
        self.label_5.setText(QCoreApplication.translate("frmMain", u"Wild group:", None))
        self.label_6.setText(QCoreApplication.translate("frmMain", u"Threads:", None))
        self.text_wrkdir.setText("")
        self.btn_load_wrkdir.setText(QCoreApplication.translate("frmMain", u"...", None))
        self.label_7.setText(QCoreApplication.translate("frmMain", u"Work path:", None))
        self.grpOutput.setTitle(QCoreApplication.translate("frmMain", u"Output", None))
        self.label_9.setText(QCoreApplication.translate("frmMain", u"Type:", None))
        self.label_10.setText(QCoreApplication.translate("frmMain", u"Sample:", None))
        self.label_11.setText(QCoreApplication.translate("frmMain", u"Chr:", None))
        self.btn_export_pic.setText(QCoreApplication.translate("frmMain", u"Export", None))
        self.btn_draw_pic.setText(QCoreApplication.translate("frmMain", u"Draw", None))
        self.tabOutput.setTabText(self.tabOutput.indexOf(self.tab_pic),
                                  QCoreApplication.translate("frmMain", u"Pictures", None))
        self.btn_save_table.setText(QCoreApplication.translate("frmMain", u"Save", None))
        self.btn_preview_table.setText(QCoreApplication.translate("frmMain", u"Preview", None))
        self.label_12.setText(QCoreApplication.translate("frmMain", u"Type:", None))
        self.label_13.setText(QCoreApplication.translate("frmMain", u"Chr:", None))
        self.label_14.setText(QCoreApplication.translate("frmMain", u"Sample:", None))
        self.tabOutput.setTabText(self.tabOutput.indexOf(self.tab_table),
                                  QCoreApplication.translate("frmMain", u"Tables", None))
        self.btn_run.setText(QCoreApplication.translate("frmMain", u"RUN", None))
    # retranslateUi
